# pylint: skip-file
PERSONALITIES_DATA = {
    "vb1": {
        "code": "VB1",
        "primary": "Visionary",
        "secondary": "The Mystical HODLer",
        "description": "Crypto or not, they believe in cosmic cycles and astrological alignments influencing markets… and occasionally, Twitter trends.",
        "traits": {
            "skin": [
                "Cosmic Purple",
                "Emerald Green",
                "Silver Glow",
                "Celestial Aura",
                "Galactic Dust",
                "Starry Night",
            ],
            "expression": [
                "Determined Stare",
                "Curious Look",
                "Mischievous Wink",
                "Serious Focus",
                "Enlightened Smile",
            ],
            "face": [
                "Starry Eyes",
                "Ethereal Glow Eyes",
                "Celestial Symbols",
                "Mystic Markings",
                "Astral Vision",
            ],
            "body": [
                "Glowing Mystic Robes",
                "Astral Cloak",
                "Druid’s Leaf Cloak",
                "Neon Circuit Suit",
                "Galactic Traveler Gear",
            ],
            "head": [
                "Galactic Aura Headpiece",
                "Crystal Crown",
                "Wizard Hat",
                "Neon Circuit Hood",
                "Space Helmet",
                "Futuristic Holographic Helmet",
            ],
        },
    },
    "vb2": {
        "code": "VB2",
        "primary": "Visionary",
        "secondary": "The Prophet of Chaos",
        "description": "Tweets dystopian predictions about society, crypto, or tech. The end of the world is always 'coming soon.'",
        "traits": {
            "skin": [
                "Cosmic Purple",
                "Midnight Blue",
                "Shadow Fade",
                "Silver Glow",
                "Shadow Phantom",
            ],
            "expression": [
                "Confident Smirk",
                "Mischievous Wink",
                "Serious Focus",
                "Suspicious Squint",
                "Evil Grin",
            ],
            "face": [
                "Cyber Visor",
                "Laser Eyes",
                "Cybernetic Eye Implant",
                "Ethereal Glow Eyes",
                "Demonic Markings",
            ],
            "body": [
                "Cyber Armor",
                "Mafia Suit",
                "Space Suit",
                "Glowing Mystic Robes",
                "Astral Cloak",
                "Neon Circuit Suit",
            ],
            "head": [
                "Cyber Horns",
                "Futuristic Holographic Helmet",
                "Wizard Hat",
                "Dragon Horns",
                "Neon Circuit Hood",
                "Galaxy Aura Headpiece",
            ],
        },
    },
    "tm1": {
        "code": "TM1",
        "primary": "Thread Master",
        "secondary": "The Conspiracy Theorist",
        "description": "Convinced that everything is manipulated—whether it’s by crypto whales or shadowy figures. Their threads blend facts with wild theories.",
        "traits": {
            "skin": ["Shadow Fade", "Charcoal Black", "Silver Glow", "Midnight Blue", "Ash Gray"],
            "expression": [
                "Suspicious Squint",
                "Determined Stare",
                "Curious Look",
                "Worried Frown",
                "Serious Focus",
            ],
            "face": ["Bandit Mask", "Tactical Goggles", "Cyber Visor", "Eyepatch", "Scar"],
            "body": [
                "Detective Trench Coat",
                "Cyber Armor",
                "Hoodie Black",
                "Steampunk Gear",
                "Ninja Gi",
            ],
            "head": [
                "Natural Raccoon Head",
                "Cyber Horns",
                "Shadow Hood",
                "Biker Helmet",
                "Top Hat",
            ],
        },
    },
    "tm2": {
        "code": "TM2",
        "primary": "Thread Master",
        "secondary": "The Trend Analyst",
        "description": "Doesn’t trade but posts in-depth analyses of market movements or explains why a particular NFT is revolutionary—or not.",
        "traits": {
            "skin": ["Silver Glow", "Ash Gray", "Midnight Blue", "Cosmic Purple"],
            "expression": ["Confident Smirk", "Curious Look", "Determined Stare", "Serious Focus"],
            "face": ["Monocle", "Cyber Visor", "Starry Eyes", "Tactical Goggles"],
            "body": ["Detective Trench Coat", "Cyber Armor", "Lab Coat", "Steampunk Gear"],
            "head": ["Wizard Hat", "Steampunk Goggles & Hat", "Cyber Horns", "Biker Helmet"],
        },
    },
    "cn1": {
        "code": "CN1",
        "primary": "Content Explorer",
        "secondary": "The Nomadic Memer",
        "description": "An endless meme generator who’s more into jokes than projects. Frequently tweets: 'ngmi' (not gonna make it).",
        "traits": {
            "skin": ["Desert Brown", "Shadow Fade", "Silver Glow", "Albino", "Rust Brown"],
            "expression": [
                "Cheeky Grin",
                "Confident Smirk",
                "Mischievous Wink",
                "Playful Tongue Out",
                "Laughing Joyfully",
            ],
            "face": ["Bandit Mask", "Winking", "Goatee", "Monocle", "Ethereal Glow Eyes"],
            "body": [
                "Hawaiian Shirt",
                "Hoodie Black",
                "Denim Vest",
                "Ninja Gi",
                "Glowing Mystic Robes",
            ],
            "head": ["Beanie", "Baseball Cap", "Top Hat", "Headphones", "Steampunk Goggles & Hat"],
        },
    },
    "cn2": {
        "code": "CN2",
        "primary": "Content Explorer",
        "secondary": "The Drama Hunter",
        "description": "Always knows the latest Crypto Twitter clash. Shares juicy screenshots with a casual '👀.'",
        "traits": {
            "skin": [
                "Shadow Fade",
                "Silver Glow",
                "Striped Wild",
                "Cosmic Purple",
                "Ash Gray",
                "Desert Brown",
            ],
            "expression": ["Curious Look", "Mischievous Wink", "Confident Smirk", "Cheeky Grin"],
            "face": ["Bandit Mask", "Eyepatch", "Tactical Goggles", "Cyber Visor"],
            "body": [
                "Cyber Armor",
                "Denim Vest",
                "Hoodie Black",
                "Detective Trench Coat",
                "Steampunk Gear",
            ],
            "head": [
                "Baseball Cap",
                "Cyber Horns",
                "Headphones",
                "Sombrero",
                "Steampunk Goggles & Hat",
            ],
        },
    },
    "cf1": {
        "code": "CF1",
        "primary": "Feed Artist",
        "secondary": "The JPEG Poet",
        "description": "Posts grandiose metaphors about NFTs or mundane moments. Examples include: 'This sunset is life’s airdrop.'",
        "traits": {
            "skin": ["Silver Glow", "Golden Shine", "Cosmic Purple", "Ice White", "Astral Aura"],
            "expression": [
                "Confident Smirk",
                "Curious Look",
                "Mischievous Wink",
                "Surprised Wide-Eyes",
                "Laughing Joyfully",
            ],
            "face": [
                "Ethereal Glow Eyes",
                "Starry Eyes",
                "Celestial Symbols",
                "Joker Smile",
                "Monocle",
            ],
            "body": [
                "Astral Cloak",
                "Neon Circuit Suit",
                "Glowing Mystic Robes",
                "Royal Cape and Sash",
                "Druid’s Leaf Cloak",
            ],
            "head": [
                "Crystal Crown",
                "Glowing Halo",
                "Galaxy Aura Headpiece",
                "Steampunk Goggles & Hat",
                "Wizard Hat",
            ],
        },
    },
    "cf2": {
        "code": "CF2",
        "primary": "Feed Artist",
        "secondary": "The Anxious Designer",
        "description": "A graphic designer or NFT artist tweeting their work with passive-aggressive captions like: 'Not sure if this is good, thoughts? 🤔'",
        "traits": {
            "skin": [
                "Ash Gray",
                "Silver Glow",
                "Desert Brown",
                "Ice White",
                "Rust Brown",
                "Shadow Phantom",
            ],
            "expression": [
                "Worried Frown",
                "Curious Look",
                "Determined Stare",
                "Neutral Calm",
                "Shy Blush",
                "Confident Smirk",
            ],
            "face": [
                "Monocle",
                "Ethereal Glow Eyes",
                "Cyber Visor",
                "Bandit Mask",
                "Scar",
                "Celestial Symbols",
            ],
            "body": [
                "Denim Vest",
                "Hoodie Black",
                "Natural Furry Raccoon",
                "Neon Circuit Suit",
                "Detective Trench Coat",
                "Lab Coat",
            ],
            "head": [
                "Beanie",
                "Cyber Horns",
                "Headphones",
                "Durag",
                "Neon Circuit Hood",
                "Wizard Hat",
            ],
        },
    },
    "sn1": {
        "code": "SN1",
        "primary": "Network Builder",
        "secondary": "The Community Builder",
        "description": "Whether it’s NFTs, crypto, or just shitposts, they’re everywhere. Starts every day with: 'gm everyone 🌞.'",
        "traits": {
            "skin": ["Silver Glow", "Striped Wild", "Desert Brown", "Rust Brown", "Midnight Blue"],
            "expression": [
                "Friendly Smile",
                "Cheeky Grin",
                "Confident Smirk",
                "Laughing Joyfully",
                "Excited Open-Mouth",
            ],
            "face": ["Bandit Mask", "Starry Eyes", "Monocle", "Tactical Goggles", "Cyber Visor"],
            "body": ["Denim Vest", "Cyber Armor", "Hawaiian Shirt", "Hoodie Black", "Ninja Gi"],
            "head": ["Beanie", "Headphones", "Baseball Cap", "Top Hat", "Steampunk Goggles & Hat"],
        },
    },
    "sn2": {
        "code": "SN2",
        "primary": "Network Builder",
        "secondary": "The Space King",
        "description": "Hosts Twitter Spaces on everything—from the latest crypto drama to philosophical debates—drawing a crowd of curious listeners.",
        "traits": {
            "skin": ["Silver Glow", "Cosmic Purple", "Ice White", "Golden Shine", "Shadow Fade"],
            "expression": [
                "Confident Smirk",
                "Curious Look",
                "Friendly Smile",
                "Determined Stare",
                "Laughing Joyfully",
            ],
            "face": ["Cyber Visor", "Monocle", "Starry Eyes", "Laser Eyes", "Ethereal Glow Eyes"],
            "body": [
                "Space Suit",
                "Royal Cape and Sash",
                "Astral Cloak",
                "Cyber Armor",
                "Neon Circuit Suit",
            ],
            "head": [
                "Crown",
                "Galaxy Aura Headpiece",
                "Cyber Horns",
                "Futuristic Holographic Helmet",
                "Crystal Crown",
            ],
        },
    },
    "ls1": {
        "code": "LS1",
        "primary": "Leader",
        "secondary": "The Shameless Shiller",
        "description": "Constantly promoting questionable projects. Their tweets are usually: 'This token will 100x by next week. Trust me, bro.'",
        "traits": {
            "skin": ["Golden Shine", "Silver Glow", "Midnight Blue", "Crimson Red"],
            "expression": [
                "Confident Smirk",
                "Cheeky Grin",
                "Excited Open-Mouth",
                "Determined Stare",
            ],
            "face": ["Bandit Mask", "Joker Smile", "Ethereal Glow Eyes", "Cyber Visor"],
            "body": ["Mafia Suit", "Cyber Armor", "Biker Jacket", "Steampunk Gear"],
            "head": ["Crown", "Top Hat", "Cyber Horns", "Viking Helmet"],
        },
    },
    "ls2": {
        "code": "LS2",
        "primary": "Leader",
        "secondary": "The Zen Influencer",
        "description": "Never loses their cool, even under heavy criticism. Posts inspiring quotes like: 'The market rises, but are you at peace?'",
        "traits": {
            "skin": ["Silver Glow", "Ice White", "Golden Shine", "Albino"],
            "expression": ["Neutral Calm", "Confident Smirk", "Friendly Smile", "Stoic Poker Face"],
            "face": ["Monocle", "Starry Eyes", "Ethereal Glow Eyes", "Celestial Symbols"],
            "body": [
                "Royal Cape and Sash",
                "Glowing Mystic Robes",
                "Natural Furry Raccoon",
                "Detective Trench Coat",
            ],
            "head": ["Crystal Crown", "Glowing Halo", "Natural Raccoon Head", "Warlock’s Hood"],
        },
    },
    "op1": {
        "code": "OP1",
        "primary": "Pragmatist",
        "secondary": "The Passive Observer",
        "description": "Retweets everything but never posts original content. Their motto: 'I’m just here for memes and threads.'",
        "traits": {
            "skin": [
                "Ash Gray",
                "Charcoal Black",
                "Desert Brown",
                "Midnight Blue",
                "Shadow Fade",
                "Silver Glow",
                "Rust Brown",
            ],
            "expression": [
                "Neutral Calm",
                "Friendly Smile",
                "Curious Look",
                "Serious Focus",
                "Shy Blush",
                "Tired Half-Lidded",
                "Stoic Poker Face",
            ],
            "face": ["Bandit Mask", "Monocle", "Tactical Goggles", "Cyber Visor", "Scar"],
            "body": [
                "Hoodie Black",
                "Denim Vest",
                "Mechanic Overalls",
                "Natural Furry Raccoon",
                "Turtleneck Green",
                "Leather Jacket",
            ],
            "head": ["Natural Raccoon Head", "Beanie", "Dreadlocks", "Headphones", "Biker Helmet"],
        },
    },
    "op2": {
        "code": "OP2",
        "primary": "Pragmatist",
        "secondary": "The Obsessive Fact-Checker",
        "description": "Only tweets to correct others with 'Actually…' Annoys everyone but is often right.",
        "traits": {
            "skin": ["Ash Gray", "Charcoal Black", "Shadow Fade", "Silver Glow"],
            "expression": [
                "Serious Focus",
                "Neutral Calm",
                "Suspicious Squint",
                "Determined Stare",
            ],
            "face": ["Monocle", "Cyber Visor", "Tactical Goggles", "Ethereal Glow Eyes"],
            "body": ["Lab Coat", "Detective Trench Coat", "Steampunk Gear", "Mechanic Overalls"],
            "head": ["Glowing Halo", "Steampunk Goggles & Hat", "Neon Circuit Hood", "Beanie"],
        },
    },
    "rc1": {
        "code": "RC1",
        "primary": "Sh*tposters",
        "secondary": "The Crypto Troll",
        "description": "Provokes maximalists and NFT enthusiasts with lines like: 'Bitcoin? Isn’t that just a JPEG?'",
        "traits": {
            "skin": [
                "Cosmic Purple",
                "Charcoal Black",
                "Desert Brown",
                "Emerald Green",
                "Rust Brown",
            ],
            "expression": [
                "Cheeky Grin",
                "Mischievous Wink",
                "Evil Grin",
                "Confident Smirk",
                "Laughing Joyfully",
            ],
            "face": ["Bandit Mask", "Joker Smile", "Cyber Visor", "Monocle", "Winking"],
            "body": ["Denim Vest", "Hoodie Black", "Biker Jacket", "Cyber Armor", "Steampunk Gear"],
            "head": ["Baseball Cap", "Beanie", "Mohawk", "Cyber Horns", "Dreadlocks"],
        },
    },
    "rc2": {
        "code": "RC2",
        "primary": "Sh*tposters",
        "secondary": "The Feed Nihilist",
        "description": "Tweets: 'Nothing matters; everything’s a bubble.' But spends 15 hours a day on Twitter watching the chaos.",
        "traits": {
            "skin": ["Charcoal Black", "Shadow Fade", "Silver Glow", "Rust Brown"],
            "expression": [
                "Cheeky Grin",
                "Mischievous Wink",
                "Confident Smirk",
                "Evil Grin",
                "Stoic Poker Face",
            ],
            "face": ["Bandit Mask", "Cyber Visor", "Joker Smile", "Monocle", "Ethereal Glow Eyes"],
            "body": [
                "Denim Vest",
                "Hoodie Black",
                "Leather Jacket",
                "Cyber Armor",
                "Neon Circuit Suit",
            ],
            "head": ["Baseball Cap", "Beanie", "Dreadlocks", "Cyber Horns", "Headphones"],
        },
    },
    "lb1": {
        "code": "LB1",
        "primary": "Drifter",
        "secondary": "The Burnout Tweeter",
        "description": "Posts 'I’m quitting Twitter' every two weeks, only to return three days later with: 'Okay, this is too addictive.'",
        "traits": {
            "skin": ["Rust Brown", "Ash Gray", "Desert Brown", "Shadow Fade"],
            "expression": [
                "Tired Half-Lidded",
                "Cheeky Grin",
                "Confident Smirk",
                "Suspicious Squint",
            ],
            "face": ["Bandit Mask", "Eyepatch", "Scar", "Tactical Goggles"],
            "body": [
                "Denim Vest",
                "Hoodie Black",
                "Detective Trench Coat",
                "Natural Furry Raccoon",
            ],
            "head": ["Beanie", "Baseball Cap", "Top Hat", "Natural Raccoon Head"],
        },
    },
    "lb2": {
        "code": "LB2",
        "primary": "Drifter",
        "secondary": "The Unfinished Threader",
        "description": "Starts writing groundbreaking threads but always ends with: 'To be continued…' (and never continues).",
        "traits": {
            "skin": ["Ash Gray", "Midnight Blue", "Shadow Fade", "Rust Brown"],
            "expression": [
                "Curious Look",
                "Mischievous Wink",
                "Serious Focus",
                "Tired Half-Lidded",
            ],
            "face": ["Bandit Mask", "Cyber Visor", "Scar", "Tactical Goggles"],
            "body": [
                "Natural Furry Raccoon",
                "Detective Trench Coat",
                "Hoodie Black",
                "Steampunk Gear",
            ],
            "head": ["Beanie", "Dreadlocks", "Baseball Cap", "Shadow Hood"],
        },
    },
    "ob1": {
        "code": "OB1",
        "primary": "Eternal Believer",
        "secondary": "The Relentless GMer",
        "description": "Tweets 'gm 🌞' every single day, no matter the bear market or controversies. A true ray of sunshine on Crypto Twitter.",
        "traits": {
            "skin": [
                "Golden Shine",
                "Ice White",
                "Emerald Green",
                "Silver Glow",
                "Albino",
                "Shadow Fade",
            ],
            "expression": [
                "Friendly Smile",
                "Excited Open-Mouth",
                "Laughing Joyfully",
                "Neutral Calm",
                "Confident Smirk",
                "Playful Tongue Out",
            ],
            "face": [
                "Starry Eyes",
                "Ethereal Glow Eyes",
                "Monocle",
                "Scar",
                "Celestial Symbols",
                "Tactical Goggles",
            ],
            "body": [
                "Natural Furry Raccoon",
                "Hawaiian Shirt",
                "Hoodie Black",
                "Glowing Mystic Robes",
                "Royal Cape and Sash",
                "Astral Cloak",
            ],
            "head": [
                "Natural Raccoon Head",
                "Crown",
                "Top Hat",
                "Glowing Halo",
                "Phoenix Feathers",
                "Wizard Hat",
            ],
        },
    },
    "ob2": {
        "code": "OB2",
        "primary": "Eternal Believer",
        "secondary": "The Naive Moonboy",
        "description": "Firmly believes 'we are early.' Tweets: 'In 10 years, we’ll all be rich!' alongside a Lambo photo.",
        "traits": {
            "skin": ["Ice White", "Silver Glow", "Cosmic Purple", "Emerald Green"],
            "expression": [
                "Excited Open-Mouth",
                "Cheeky Grin",
                "Surprised Wide-Eyes",
                "Curious Look",
            ],
            "face": ["Starry Eyes", "Ethereal Glow Eyes", "Monocle", "Celestial Symbols"],
            "body": ["Astral Cloak", "Hawaiian Shirt", "Space Suit", "Neon Circuit Suit"],
            "head": ["Wizard Hat", "Top Hat", "Cyber Horns", "Glowing Halo"],
        },
    },
    "rt1": {
        "code": "RT1",
        "primary": "Salty Tweeter",
        "secondary": "The Professional Hater",
        "description": "Criticizes everything and everyone without offering solutions. A favorite phrase: 'This project was dead before it even started.'",
        "traits": {
            "skin": ["Shadow Fade", "Charcoal Black", "Ash Gray", "Silver Glow", "Midnight Blue"],
            "expression": [
                "Angry Snarl",
                "Suspicious Squint",
                "Evil Grin",
                "Worried Frown",
                "Stoic Poker Face",
            ],
            "face": [
                "Scar",
                "Bandit Mask",
                "Ethereal Glow Eyes",
                "Cybernetic Eye Implant",
                "Tactical Goggles",
            ],
            "body": [
                "Biker Jacket",
                "Detective Trench Coat",
                "Cyber Armor",
                "Leather Jacket",
                "Shadow Assassin Outfit",
            ],
            "head": ["Cyber Horns", "Beanie", "Viking Helmet", "Top Hat", "Shadow Hood"],
        },
    },
    "rt2": {
        "code": "RT2",
        "primary": "Salty Tweeter",
        "secondary": "The Perpetually Disappointed",
        "description": "Invested in 10 flopped projects. Tweets reek of bitterness: 'Another rug pull. We’re all doomed.'",
        "traits": {
            "skin": ["Shadow Fade", "Charcoal Black", "Midnight Blue"],
            "expression": ["Worried Frown", "Angry Snarl", "Suspicious Squint"],
            "face": ["Scar", "Monocle", "Evil Grin"],
            "body": ["Detective Trench Coat", "Leather Jacket", "Cyber Armor"],
            "head": ["Shadow Hood", "Baseball Cap", "Beanie"],
        },
    },
    "dt1": {
        "code": "DT1",
        "primary": "Deep Thinker",
        "secondary": "The Algorithm Poet",
        "description": "Turns complex concepts into haikus or quotes. Example: 'A token in flight. Why catch it if it’s already fallen?'",
        "traits": {
            "skin": [
                "Cosmic Purple",
                "Midnight Blue",
                "Ice White",
                "Silver Glow",
                "Ethereal Glow",
                "Shadow Fade",
            ],
            "expression": [
                "Neutral Calm",
                "Curious Look",
                "Serious Focus",
                "Thoughtful Gaze",
                "Shy Blush",
                "Introspective Smile",
            ],
            "face": [
                "Monocle",
                "Celestial Symbols",
                "Ethereal Glow Eyes",
                "Cyber Visor",
                "Philosopher's Mask",
                "Winking",
            ],
            "body": [
                "Hoodie Black",
                "Steampunk Gear",
                "Cyber Armor",
                "Philosopher's Robe",
                "Astral Cloak",
                "Turtleneck Green",
            ],
            "head": [
                "Natural Raccoon Head",
                "Wizard Hat",
                "Crown",
                "Top Hat",
                "Neon Circuit Hood",
                "Galaxy Aura Headpiece",
            ],
        },
    },
    "dt2": {
        "code": "DT2",
        "primary": "Deep Thinker",
        "secondary": "The Cryptic Oracle",
        "description": "Posts vague tweets like: 'Those who know, know. 🌑' to intrigue everyone.",
        "traits": {
            "skin": [
                "Midnight Blue",
                "Shadow Fade",
                "Cosmic Purple",
                "Ice White",
                "Shadow Phantom",
            ],
            "expression": [
                "Serious Focus",
                "Suspicious Squint",
                "Stoic Poker Face",
                "Worried Frown",
                "Neutral Calm",
            ],
            "face": [
                "Scar",
                "Ethereal Glow Eyes",
                "Celestial Symbols",
                "Demonic Markings",
                "Monocle",
            ],
            "body": [
                "Astral Cloak",
                "Cyber Armor",
                "Detective Trench Coat",
                "Glowing Mystic Robes",
                "Shadow Assassin Outfit",
            ],
            "head": [
                "Wizard Hat",
                "Crystal Crown",
                "Shadow Hood",
                "Galaxy Aura Headpiece",
                "Futuristic Holographic Helmet",
            ],
        },
    },
    "cj1": {
        "code": "CJ1",
        "primary": "Engagement Chaser",
        "secondary": "The Retweet Hunter",
        "description": "Creates ridiculous polls or tweets like: 'Like for Bitcoin, retweet for Ethereum.' Anything for stats.",
        "traits": {
            "skin": ["Silver Glow", "Cosmic Purple", "Ice White", "Neon Circuit", "Golden Shine"],
            "expression": [
                "Cheeky Grin",
                "Mischievous Wink",
                "Excited Open-Mouth",
                "Confident Smirk",
                "Playful Tongue Out",
            ],
            "face": [
                "Starry Eyes",
                "Joker Smile",
                "Cyber Visor",
                "Ethereal Glow Eyes",
                "Tactical Goggles",
            ],
            "body": [
                "Cyber Armor",
                "Neon Circuit Suit",
                "Space Suit",
                "Steampunk Gear",
                "Astral Cloak",
            ],
            "head": [
                "Headphones",
                "Cyber Horns",
                "Futuristic Holographic Helmet",
                "Neon Circuit Hood",
                "Glowing Halo",
            ],
        },
    },
    "cj2": {
        "code": "CJ2",
        "primary": "Engagement Chaser",
        "secondary": "The Thread Spammer",
        "description": "Posts overly long threads, sometimes completely off-topic, like: 'How the history of pyramids explains Dogecoin.'",
        "traits": {
            "skin": ["Golden Shine", "Cosmic Purple", "Silver Glow", "Electric Blue"],
            "expression": ["Excited Open-Mouth", "Curious Look", "Mischievous Wink", "Cheeky Grin"],
            "face": ["Starry Eyes", "Bandit Mask", "Cyber Visor", "Joker Smile"],
            "body": ["Hawaiian Shirt", "Cyber Armor", "Neon Circuit Suit", "Natural Furry Raccoon"],
            "head": ["Headphones", "Top Hat", "Futuristic Holographic Helmet", "Mohawk"],
        },
    },
    "sh1": {
        "code": "SH1",
        "primary": "Deal Seeker",
        "secondary": "The Opportunistic Minimalist",
        "description": "Only tweets to ask: 'Alpha, GMX, or airdrops—who’s got the hookup?' and rarely interacts otherwise.",
        "traits": {
            "skin": ["Ash Gray", "Desert Brown", "Striped Wild", "Rust Brown"],
            "expression": [
                "Neutral Calm",
                "Mischievous Wink",
                "Suspicious Squint",
                "Confident Smirk",
            ],
            "face": ["Bandit Mask", "Monocle", "Goatee", "Winking"],
            "body": ["Natural Furry Raccoon", "Denim Vest", "Biker Jacket", "Hoodie Black"],
            "head": ["Baseball Cap", "Beanie", "Durag", "Dreadlocks"],
        },
    },
    "sh2": {
        "code": "SH2",
        "primary": "Deal Seeker",
        "secondary": "The Bag Holder Hunter",
        "description": "Subtly pushes people to buy their tokens before selling: 'This project is a hidden gem, but DYOR.'",
        "traits": {
            "skin": ["Silver Glow", "Charcoal Black", "Desert Brown", "Albino", "Shadow Phantom"],
            "expression": [
                "Confident Smirk",
                "Mischievous Wink",
                "Cheeky Grin",
                "Stoic Poker Face",
                "Curious Look",
            ],
            "face": [
                "Bandit Mask",
                "Monocle",
                "Ethereal Glow Eyes",
                "Tactical Goggles",
                "Laser Eyes",
            ],
            "body": [
                "Mafia Suit",
                "Detective Trench Coat",
                "Hoodie Black",
                "Biker Jacket",
                "Cyber Armor",
            ],
            "head": [
                "Top Hat",
                "Natural Raccoon Head",
                "Cyber Horns",
                "Space Helmet",
                "Steampunk Goggles & Hat",
            ],
        },
    },
    "na1": {
        "code": "NA1",
        "primary": "Narcissist",
        "secondary": "The Profit Flexer",
        "description": "Shares screenshots of their winning trades (never losses). Classic line: 'Easy money.'",
        "traits": {
            "skin": [
                "Golden Shine",
                "Charcoal Black",
                "Silver Glow",
                "Emerald Green",
                "Crimson Red",
            ],
            "expression": [
                "Confident Smirk",
                "Cheeky Grin",
                "Evil Grin",
                "Mischievous Wink",
                "Stoic Poker Face",
            ],
            "face": ["Bandit Mask", "Monocle", "Joker Smile", "Ethereal Glow Eyes", "Starry Eyes"],
            "body": [
                "Mafia Suit",
                "Leather Jacket",
                "Space Suit",
                "Royal Cape and Sash",
                "Astral Cloak",
            ],
            "head": ["Crown", "Top Hat", "Cyber Horns", "Crystal Crown", "Viking Helmet"],
        },
    },
    "na2": {
        "code": "NA2",
        "primary": "Narcissist",
        "secondary": "The Viral King",
        "description": "Posts generic engagement tweets like: 'The three rules of success: 1) Work hard. 2) Persevere. 3) Buy NFTs.'",
        "traits": {
            "skin": ["Golden Shine", "Silver Glow", "Midnight Blue", "Ice White"],
            "expression": ["Confident Smirk", "Cheeky Grin", "Evil Grin", "Laughing Joyfully"],
            "face": ["Ethereal Glow Eyes", "Monocle", "Starry Eyes", "Cybernetic Eye Implant"],
            "body": ["Mafia Suit", "Leather Jacket", "Cyber Armor", "Royal Cape and Sash"],
            "head": ["Crown", "Top Hat", "Samurai Helmet", "Glowing Halo"],
        },
    },
    "cb1": {
        "code": "CB1",
        "primary": "Chaos Bringer",
        "secondary": "The All-Purpose Troll",
        "description": "Tweets absurdities like: 'Blockchain is just Excel with extra steps.' purely for laughs.",
        "traits": {
            "skin": [
                "Desert Brown",
                "Crimson Red",
                "Cosmic Purple",
                "Shadow Phantom",
                "Albino",
                "Striped Wild",
            ],
            "expression": [
                "Laughing Joyfully",
                "Mischievous Wink",
                "Evil Grin",
                "Playful Tongue Out",
                "Cheeky Grin",
                "Surprised Wide-Eyes",
            ],
            "face": [
                "Joker Smile",
                "Clown Makeup",
                "Bandit Mask",
                "Scar",
                "Ethereal Glow Eyes",
                "Demonic Markings",
            ],
            "body": [
                "Cyborg Armor",
                "Hawaiian Shirt",
                "Biker Jacket",
                "Space Suit",
                "Steampunk Gear",
                "Neon Circuit Suit",
            ],
            "head": [
                "Mohawk",
                "Biker Helmet",
                "Crown",
                "Cyber Horns",
                "Sombrero",
                "Flaming Spirit Head",
            ],
        },
    },
    "cb2": {
        "code": "CB2",
        "primary": "Chaos Bringer",
        "secondary": "The War Instigator",
        "description": "Fuels debates between blockchain maximalists just to watch the chaos unfold.",
        "traits": {
            "skin": ["Crimson Red", "Charcoal Black", "Shadow Fade", "Rust Brown"],
            "expression": ["Mischievous Wink", "Confident Smirk", "Evil Grin"],
            "face": ["Bandit Mask", "Scar", "Ethereal Glow Eyes"],
            "body": ["Cyber Armor", "Biker Jacket", "Mafia Suit"],
            "head": ["Cyber Horns", "Viking Helmet", "Dreadlocks"],
        },
    },
    "oa1": {
        "code": "OA1",
        "primary": "Overthinker",
        "secondary": "The Refresh Addict",
        "description": "Spends all day refreshing crypto portfolios and tweets every micro-change as breaking news.",
        "traits": {
            "skin": ["Silver Glow", "Ice White", "Blue Steel", "Ash Gray"],
            "expression": [
                "Worried Frown",
                "Suspicious Squint",
                "Serious Focus",
                "Tired Half-Lidded",
            ],
            "face": ["Tactical Goggles", "Monocle", "Cyber Visor", "Ethereal Glow Eyes"],
            "body": [
                "Cybernetic Raccoon Torso",
                "Detective Trench Coat",
                "Denim Vest",
                "Neon Circuit Suit",
            ],
            "head": ["Cybernetic Helmet", "Steampunk Goggles & Hat", "Beanie", "Headphones"],
        },
    },
    "oa2": {
        "code": "OA2",
        "primary": "Overthinker",
        "secondary": "The Paranoid Survivor",
        "description": "Always worried about getting hacked. Tweets: 'Be careful with all links! Even a .jpg could ruin you.'",
        "traits": {
            "skin": ["Shadow Fade", "Silver Glow", "Ash Gray", "Charcoal Black"],
            "expression": [
                "Suspicious Squint",
                "Worried Frown",
                "Serious Focus",
                "Stoic Poker Face",
            ],
            "face": ["Tactical Goggles", "Cyber Visor", "Scar", "Monocle"],
            "body": ["Cyber Armor", "Detective Trench Coat", "Hoodie Black", "Steampunk Gear"],
            "head": ["Cybernetic Helmet", "Shadow Hood", "Biker Helmet", "Beanie"],
        },
    },
    "rh1": {
        "code": "RH1",
        "primary": "Comeback Hero",
        "secondary": "The Reformed Shitcoiner",
        "description": "Formerly obsessed with shitcoins, now tweets: 'I’m focusing on solid projects only. No more nonsense.'",
        "traits": {
            "skin": ["Shadow Fade", "Silver Glow", "Charcoal Black", "Rust Brown", "Ash Gray"],
            "expression": [
                "Determined Stare",
                "Confident Smirk",
                "Serious Focus",
                "Neutral Calm",
                "Stoic Poker Face",
            ],
            "face": [
                "Bandit Mask",
                "Scar",
                "Cybernetic Eye Implant",
                "Monocle",
                "Tactical Goggles",
            ],
            "body": [
                "Natural Furry Raccoon",
                "Detective Trench Coat",
                "Leather Jacket",
                "Mafia Suit",
                "Cyber Armor",
            ],
            "head": ["Baseball Cap", "Beanie", "Top Hat", "Viking Helmet", "Wizard Hat"],
        },
    },
    "rh2": {
        "code": "RH2",
        "primary": "Comeback Hero",
        "secondary": "The Patience Preacher",
        "description": "Tweets: 'Time in the market beats timing the market.' after losing big on aggressive trades.",
        "traits": {
            "skin": ["Silver Glow", "Shadow Fade", "Charcoal Black"],
            "expression": ["Determined Stare", "Confident Smirk", "Serious Focus"],
            "face": ["Scar", "Monocle", "Ethereal Glow Eyes"],
            "body": ["Mafia Suit", "Detective Trench Coat", "Turtleneck Green"],
            "head": ["Natural Raccoon Head", "Crown", "Top Hat"],
        },
    },
    "pt1": {
        "code": "PT1",
        "primary": "Pretender",
        "secondary": "The Fake Expert",
        "description": "Posts charts and technical jargon to sound smart, but everyone knows they’re clueless.",
        "traits": {
            "skin": ["Charcoal Black", "Striped Wild", "Albino", "Shadow Phantom"],
            "expression": [
                "Confident Smirk",
                "Neutral Calm",
                "Mischievous Wink",
                "Stoic Poker Face",
            ],
            "face": ["Monocle", "Joker Smile", "Cyber Visor", "Scar"],
            "body": ["Detective Trench Coat", "Lab Coat", "Biker Jacket", "Royal Cape and Sash"],
            "head": ["Top Hat", "Wizard Hat", "Sombrero", "Baseball Cap"],
        },
    },
    "pt2": {
        "code": "PT2",
        "primary": "Pretender",
        "secondary": "The Feed Copycat",
        "description": "Copies viral tweets from others and hopes no one notices. Sometimes their version performs better.",
        "traits": {
            "skin": ["Silver Glow", "Striped Wild", "Shadow Fade"],
            "expression": [
                "Cheeky Grin",
                "Mischievous Wink",
                "Confident Smirk",
                "Stoic Poker Face",
            ],
            "face": ["Bandit Mask", "Joker Smile", "Ethereal Glow Eyes"],
            "body": ["Natural Furry Raccoon", "Steampunk Gear", "Neon Circuit Suit"],
            "head": [
                "Natural Raccoon Head",
                "Cybernetic Helmet",
                "Dreadlocks",
                "Steampunk Goggles & Hat",
            ],
        },
    },
    "gh1": {
        "code": "GH1",
        "primary": "Ghost",
        "secondary": "The Abandoned Account",
        "description": "Last tweeted in 2018 but holds rare NFTs. Everyone wonders why they haven’t sold them yet.",
        "traits": {
            "skin": ["Ice White", "Shadow Fade", "Ghostly Transparent Body", "Shadow Phantom"],
            "expression": [
                "Stoic Poker Face",
                "Neutral Calm",
                "Worried Frown",
                "Suspicious Squint",
            ],
            "face": ["Ethereal Glow Eyes", "Scar", "Skull Face Paint", "Shadow Hood"],
            "body": [
                "Ghostly Transparent Body",
                "Hoodie Black",
                "Detective Trench Coat",
                "Etherial Glow Eyes",
            ],
            "head": [
                "Natural Raccoon Head",
                "Shadow Hood",
                "Dreadlocks",
                "Ghostly Transparent Body",
                "Bone Mask",
            ],
        },
    },
    "gh2": {
        "code": "GH2",
        "primary": "Ghost",
        "secondary": "The Backseat Trader",
        "description": "Only tweets after the fact: 'I saw this coming. Shame I didn’t post earlier.'",
        "traits": {
            "skin": ["Albino", "Shadow Phantom", "Ghostly Transparent Body"],
            "expression": ["Neutral Calm", "Serious Focus", "Stoic Poker Face"],
            "face": ["Ethereal Glow Eyes", "Scar", "Monocle"],
            "body": ["Detective Trench Coat", "Hoodie Black", "Ghostly Transparent Body"],
            "head": ["Top Hat", "Shadow Hood", "Neon Circuit Hood"],
        },
    },
}
